# Generated by Django 5.2.7 on 2025-10-15 21:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('functions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cpu_rate_per_hour', models.DecimalField(decimal_places=6, default=Decimal('0.002'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('memory_rate_per_gb_hour', models.DecimalField(decimal_places=6, default=Decimal('0.001'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('cold_start_penalty', models.DecimalField(decimal_places=6, default=Decimal('0.005'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('platform_fee_rate', models.DecimalField(decimal_places=3, default=Decimal('1.3'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.0'))])),
                ('min_efficiency_factor', models.DecimalField(decimal_places=2, default=Decimal('0.7'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))])),
                ('max_efficiency_factor', models.DecimalField(decimal_places=2, default=Decimal('1.3'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('1.0'))])),
                ('cold_start_base_cost', models.DecimalField(decimal_places=6, default=Decimal('0.002'), max_digits=10)),
                ('cold_start_queue_factor', models.DecimalField(decimal_places=3, default=Decimal('1.5'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CALCULATED', 'Calculated'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid')], default='PENDING', max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'start_date', 'end_date')},
            },
        ),
        migrations.CreateModel(
            name='FunctionBillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_hours', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=12)),
                ('memory_gb_hours', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=12)),
                ('cold_start_count', models.IntegerField(default=0)),
                ('average_efficiency', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5)),
                ('cpu_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=12)),
                ('memory_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=12)),
                ('cold_start_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=12)),
                ('efficiency_factor', models.DecimalField(decimal_places=3, default=Decimal('1.0'), max_digits=5)),
                ('base_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=12)),
                ('final_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='function_records', to='billing.billingperiod')),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.function')),
            ],
            options={
                'indexes': [models.Index(fields=['function', 'billing_period'], name='billing_fun_functio_75d555_idx'), models.Index(fields=['created_at'], name='billing_fun_created_fc93bd_idx')],
                'unique_together': {('function', 'billing_period')},
            },
        ),
        migrations.CreateModel(
            name='HourlyFunctionMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('cpu_seconds', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('memory_byte_seconds', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('cold_start_count', models.IntegerField(default=0)),
                ('pod_seconds', models.DecimalField(decimal_places=4, default=0, max_digits=15)),
                ('raw_metrics', models.JSONField(default=dict)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functions.function')),
            ],
            options={
                'indexes': [models.Index(fields=['function', 'timestamp'], name='billing_hou_functio_28c612_idx'), models.Index(fields=['timestamp'], name='billing_hou_timesta_291809_idx')],
                'unique_together': {('function', 'timestamp')},
            },
        ),
    ]
