apiVersion: apps/v1
kind: Deployment
metadata:
  name: faas-billing-django
  labels:
    app: faas-billing-django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: faas-billing-django
  template:
    metadata:
      labels:
        app: faas-billing-django
    spec:
      containers:
      - name: django
        image: faas-billing-django:latest  # Локальный образ
        ports:
        - containerPort: 8000
        env:
        - name: DEBUG
          value: "False"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: secret-key
        - name: DB_NAME
          value: "faas_billing"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secrets
              key: db-password
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: KUBERNETES_SERVICE_HOST
          value: "kubernetes.default.svc"
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
---
apiVersion: v1
kind: Service
metadata:
  name: faas-billing-service
spec:
  selector:
    app: faas-billing-django
  ports:
  - port: 80
    targetPort: 8000