apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  secret-key: eW91ci1zZWNyZXQta2V5LWhlcmU=  # echo -n 'your-secret-key-here' | base64
  db-password: MTIzMTIz  # echo -n '123123' | base64