# Generated by Django 5.2.7 on 2025-10-15 21:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tier', models.CharField(choices=[('STARTER', 'Starter'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cpu_rate_per_hour', models.DecimalField(decimal_places=6, default=Decimal('0.002'), max_digits=10)),
                ('memory_rate_per_gb_hour', models.DecimalField(decimal_places=6, default=Decimal('0.001'), max_digits=10)),
                ('cold_start_penalty', models.DecimalField(decimal_places=6, default=Decimal('0.005'), max_digits=10)),
                ('platform_fee_rate', models.DecimalField(decimal_places=3, default=Decimal('1.3'), max_digits=5)),
                ('min_efficiency_factor', models.DecimalField(decimal_places=2, default=Decimal('0.7'), max_digits=3)),
                ('max_efficiency_factor', models.DecimalField(decimal_places=2, default=Decimal('1.3'), max_digits=3)),
                ('max_functions', models.IntegerField(default=10)),
                ('max_cpu_per_function', models.IntegerField(default=2000)),
                ('max_memory_per_function', models.IntegerField(default=2147483648)),
                ('max_scale', models.IntegerField(default=10)),
                ('includes_support', models.BooleanField(default=False)),
                ('includes_analytics', models.BooleanField(default=False)),
                ('includes_sla', models.BooleanField(default=False)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('functions_used', models.IntegerField(default=0)),
                ('cpu_used', models.IntegerField(default=0)),
                ('memory_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tariff_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarif_plan.tariffplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usersubscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'db_table': 'user_subscriptions',
            },
        ),
    ]
