# Generated by Django 5.2.7 on 2025-10-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
