# Generated by Django 5.2.7 on 2025-10-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarif_plan', '0002_tariffplan_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffplan',
            name='max_memory_per_function',
            field=models.BigIntegerField(default=2147483648),
        ),
    ]
