# Generated by Django 5.2.7 on 2025-10-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Function",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("docker_image", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DEPLOYING", "Deploying"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                            ("DELETING", "Deleting"),
                        ],
                        default="DEPLOYING",
                        max_length=20,
                    ),
                ),
                ("knative_service_name", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True)),
                ("min_scale", models.IntegerField(default=0)),
                ("max_scale", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
