# Generated by Django 5.2.7 on 2025-10-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("functions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="function",
            name="metrics",
            field=models.JSONField(default={}),
        ),
    ]
